# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: vibhatha@gmail.com
author_name: Vibhatha Abeykoon
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_ext_001
project_short_description: A JupyterLab extension.
python_name: jupyterlabext001
repository: https://github.com/vibhatha/jupyterlab_ext_001
test: true

